//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.22 at 10:20:05 AM CST 
//


package com.itq.seguimientopaquetes.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="idCliente"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]+"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="apellidoMaterno" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="apellidoPaterno" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="direccion"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="calle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="numeroInterior" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="numeroExterior" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="codigoPostal" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="colonia" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="municipio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="estado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="pais" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="email"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="telefono" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechaNac"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="diaNac" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="mesNac" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="yearNac" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idCliente",
    "nombre",
    "apellidoMaterno",
    "apellidoPaterno",
    "direccion",
    "email",
    "telefono",
    "fechaNac",
    "password"
})
@XmlRootElement(name = "cliente")
public class Cliente {

    @XmlElement(required = true)
    protected String idCliente;
    @XmlElement(required = true)
    protected String nombre;
    @XmlElement(required = true)
    protected String apellidoMaterno;
    @XmlElement(required = true)
    protected String apellidoPaterno;
    @XmlElement(required = true)
    protected Cliente.Direccion direccion;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String telefono;
    @XmlElement(required = true)
    protected Cliente.FechaNac fechaNac;
    @XmlElement(required = true)
    protected String password;

    /**
     * Gets the value of the idCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdCliente() {
        return idCliente;
    }

    /**
     * Sets the value of the idCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdCliente(String value) {
        this.idCliente = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the apellidoMaterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApellidoMaterno() {
        return apellidoMaterno;
    }

    /**
     * Sets the value of the apellidoMaterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApellidoMaterno(String value) {
        this.apellidoMaterno = value;
    }

    /**
     * Gets the value of the apellidoPaterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApellidoPaterno() {
        return apellidoPaterno;
    }

    /**
     * Sets the value of the apellidoPaterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApellidoPaterno(String value) {
        this.apellidoPaterno = value;
    }

    /**
     * Gets the value of the direccion property.
     * 
     * @return
     *     possible object is
     *     {@link Cliente.Direccion }
     *     
     */
    public Cliente.Direccion getDireccion() {
        return direccion;
    }

    /**
     * Sets the value of the direccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cliente.Direccion }
     *     
     */
    public void setDireccion(Cliente.Direccion value) {
        this.direccion = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the telefono property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * Sets the value of the telefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefono(String value) {
        this.telefono = value;
    }

    /**
     * Gets the value of the fechaNac property.
     * 
     * @return
     *     possible object is
     *     {@link Cliente.FechaNac }
     *     
     */
    public Cliente.FechaNac getFechaNac() {
        return fechaNac;
    }

    /**
     * Sets the value of the fechaNac property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cliente.FechaNac }
     *     
     */
    public void setFechaNac(Cliente.FechaNac value) {
        this.fechaNac = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="calle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="numeroInterior" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="numeroExterior" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="codigoPostal" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="colonia" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="municipio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="estado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="pais" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "calle",
        "numeroInterior",
        "numeroExterior",
        "codigoPostal",
        "colonia",
        "municipio",
        "estado",
        "pais"
    })
    public static class Direccion {

        @XmlElement(required = true)
        protected String calle;
        protected Integer numeroInterior;
        protected int numeroExterior;
        protected int codigoPostal;
        @XmlElement(required = true)
        protected String colonia;
        @XmlElement(required = true)
        protected String municipio;
        @XmlElement(required = true)
        protected String estado;
        @XmlElement(required = true)
        protected String pais;

        /**
         * Gets the value of the calle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCalle() {
            return calle;
        }

        /**
         * Sets the value of the calle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCalle(String value) {
            this.calle = value;
        }

        /**
         * Gets the value of the numeroInterior property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNumeroInterior() {
            return numeroInterior;
        }

        /**
         * Sets the value of the numeroInterior property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumeroInterior(Integer value) {
            this.numeroInterior = value;
        }

        /**
         * Gets the value of the numeroExterior property.
         * 
         */
        public int getNumeroExterior() {
            return numeroExterior;
        }

        /**
         * Sets the value of the numeroExterior property.
         * 
         */
        public void setNumeroExterior(int value) {
            this.numeroExterior = value;
        }

        /**
         * Gets the value of the codigoPostal property.
         * 
         */
        public int getCodigoPostal() {
            return codigoPostal;
        }

        /**
         * Sets the value of the codigoPostal property.
         * 
         */
        public void setCodigoPostal(int value) {
            this.codigoPostal = value;
        }

        /**
         * Gets the value of the colonia property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColonia() {
            return colonia;
        }

        /**
         * Sets the value of the colonia property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColonia(String value) {
            this.colonia = value;
        }

        /**
         * Gets the value of the municipio property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMunicipio() {
            return municipio;
        }

        /**
         * Sets the value of the municipio property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMunicipio(String value) {
            this.municipio = value;
        }

        /**
         * Gets the value of the estado property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstado() {
            return estado;
        }

        /**
         * Sets the value of the estado property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstado(String value) {
            this.estado = value;
        }

        /**
         * Gets the value of the pais property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPais() {
            return pais;
        }

        /**
         * Sets the value of the pais property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPais(String value) {
            this.pais = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="diaNac" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="mesNac" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="yearNac" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "diaNac",
        "mesNac",
        "yearNac"
    })
    public static class FechaNac {

        protected int diaNac;
        protected int mesNac;
        protected int yearNac;

        /**
         * Gets the value of the diaNac property.
         * 
         */
        public int getDiaNac() {
            return diaNac;
        }

        /**
         * Sets the value of the diaNac property.
         * 
         */
        public void setDiaNac(int value) {
            this.diaNac = value;
        }

        /**
         * Gets the value of the mesNac property.
         * 
         */
        public int getMesNac() {
            return mesNac;
        }

        /**
         * Sets the value of the mesNac property.
         * 
         */
        public void setMesNac(int value) {
            this.mesNac = value;
        }

        /**
         * Gets the value of the yearNac property.
         * 
         */
        public int getYearNac() {
            return yearNac;
        }

        /**
         * Sets the value of the yearNac property.
         * 
         */
        public void setYearNac(int value) {
            this.yearNac = value;
        }

    }

}
