<?xml version="1.0" encoding="UTF-8"?>
<!--Aqui va operaciones crearUbicacion -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://com.rastreo"
	targetNamespace="http://com.rastreo">
	<wsdl:types>
		<xs:schema targetNamespace="http://com.rastreo" elementFormDefault="qualified">
			<xs:include schemaLocation="commons.xsd" />
			<xs:include schemaLocation="ubicacion.xsd" />
		</xs:schema>
	</wsdl:types>

	<wsdl:message name="creacionUbicacionRequest">
		<wsdl:part name="parameter" type="tns:ubicacion" />
	</wsdl:message>

	<wsdl:message name="creacionUbicacionResponse">
		<wsdl:part name="parameter" type="tns:ack" />
	</wsdl:message>

	<wsdl:portType name="paquetePortType">

		<wsdl:operation name="creacionUbicacionOperation">
			<wsdl:input message="tns:creacionUbicacionRequest" />
			<wsdl:output message="tns:creacionUbicacionResponse" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="ubiacionBinding" type="tns:paquetePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="creacionUbicacionOperation">
			<soap:operation soapAction="urn:#NewOperation" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="RastreoService">
		<wsdl:port name="RastreoPort" binding="tns:ubiacionBinding">
			<soap:address location="No target address" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>